### ISSUE TITLE
View source button/ribbon

### ISSUE THREAD

**Issue by Pepijn98** [KurozeroPB/Projekt-RED#1]
Add a `view source code` "button" in the top right corner

**Comment by Pepijn98** [comment]
This should work

```html
<a class="ribbon" href="https://github.com/KurozeroPB/Projekt-RED" target="_blank">
    <b-icon pack="fab" icon="github" />
    View source
</a>
```

```scss
body {
    overflow-x: hidden;
}

.ribbon {
    margin: 0;
    padding: 0;
    background: var(--black);
    color: var(--white);
    padding: 1em 0;
    position: absolute;
    top: 0;
    right: 0;
    transform: translateX(30%) translateY(0%) rotate(45deg);
    transform-origin: top left;

    &:hover {
        color: var(--white);
    }

    &::before,
    &::after {
        content: '';
        position: absolute;
        top: 0;
        margin: 0 -1px;
        width: 100%;
        height: 100%;
        background: var(--black);
    }

    &::before {
        right: 100%;
    }

    &::after {
        left: 100%;
    }
}
```
